INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Niccolò', 'Barella', NULL, 'Centrocampista');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Alessio', 'Cragno', NULL, 'Portiere');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Romelu', 'Lukaku', NULL, 'Attaccante');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Andrea', 'Belotti', NULL, 'Attaccante');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Giovanni', 'Di Lorenzo', NULL, 'Difensore');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Charles', 'De Ketelaere', NULL, 'Attaccante');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Marten', 'De Roon', NULL, 'Centrocampista');  
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Remo', 'Freuler', NULL, 'Centrocampista');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Lorenzo', 'Pellegrini', NULL, 'Centrocampista');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Gianluca', 'Mancini', NULL, 'Difensore');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Leonardo', 'Spinazzola', NULL, 'Difensore');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Mike', 'Maignan', NULL, 'Portiere');
INSERT INTO `GIOCATORE` (`id`, `nome`, `cognome`, `SQUADRA_nome`, `ruolo`) VALUES (NULL, 'Ivan', 'Provedel', NULL, 'Portiere');